### ISSUE TITLE
Out of Memory Error no matter the Batch Size

### ISSUE THREAD

**Issue by TrackLab** [deepak112/Keras-SRGAN#14]
Hello.

I had some trouble to find the code that defines the batch size, but I found it.
The Problem is that I always get a Out of Memory Error when running the Script, no matter the batch_size.

Maybe you know what to do, because I am helpless at this point.
Here is the Error Log. It is really big, so I give a link to the pastebin.

https://pastebin.com/qvvCcc59

Thanks for any help.

**Comment by paulbonnard** [comment]
Hello, you have to look a the discriminator, this is the model which takes the larger images so it has the largest number of parameters, i managed to launch the entire model on a single gpu with moving the dicriminator.trainable in the train and not in the models

If you have oom error, try to reduce the size of your models and the size of your images untils you find where the issue comes from

**Comment by TrackLab** [comment]
> 
> 
> Hello, you have to look a the discriminator, this is the model which takes the larger images so it has the largest number of parameters, i managed to launch the entire model on a single gpu with moving the dicriminator.trainable in the train and not in the models
> 
> If you have oom error, try to reduce the size of your models and the size of your images untils you find where the issue comes from

Hey, sorry for the late reply.
Just for the sake of trying I changed the Images Size to 32x32. That is the smallest the Network can take.
Running this actually makes the Network train for 1 Epoch, in the matter of 2 seconds.
Right after finishing Epoch 1 it prints out 3 lines of Info which are 

> discriminator_loss : 0.407232
> gan_loss : [0.08374723, 0.08203116, 1.7160668]
> 0

But in the same second it throws an Error and stops the Script. And I have no Idea what that Error is trying to tell me...

`Traceback (most recent call last):
  File "train.py", line 131, in <module>
    train(values.epochs, values.batch_size, values.input_dir, values.output_dir, values.model_save_dir, values.number_of_images, values.train_test_ratio)
  File "train.py", line 98, in train
    Utils.plot_generated_images(output_dir, e, generator, x_test_hr, x_test_lr)
  File "D:\Python Projects\2019\May\SRGAN - Kopie\Utils.py", line 158, in plot_generated_images
    value = randint(0, examples)
  File "mtrand.pyx", line 993, in mtrand.RandomState.randint
ValueError: low >= high`

**Comment by paulbonnard** [comment]
check what examples is, it has to be an integer > 0

**Comment by TrackLab** [comment]
> 
> 
> check what examples is, it has to be an integer > 0

I think that is the 0 that has been printed in the console. 
examples gets defined in the plot_generated_images function and is this:
`examples = x_test_hr.shape[0]`

**Comment by rophen2333** [comment]
I have same problem。

**Comment by ajinkya933** [comment]
I have same error the code is not optimised I am using GTX 1080TI 12 GB ddr5 ram. System RAM 8GB. Batch size =1 image size: 384x384
