### ISSUE TITLE
GPU OOM

### ISSUE THREAD

**Issue by rophen2333** [deepak112/Keras-SRGAN#25]
Hello, I want to ask why my nvidia Titan xp GPU 11G memory, why the training went to the second round and the memory overflowed.

**Comment by tripzero** [comment]
try with smaller batch size?

**Comment by tripzero** [comment]
Another thing I did besides reduce the batch size was add the following to train.py:
```python
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.per_process_gpu_memory_fraction = 2
session = tf.compat.v1.Session(graph=tf.Graph(), config=config)
```

This tells CUDA to try to use system memory as swap when it runs out of GPU memory.
