### ISSUE TITLE
ValueError: Error when checking input: expected input_12 to have 4 dimensions, but got array with shape (4, 1)

### ISSUE THREAD

**Issue by sandhya9173** [deepak112/Keras-SRGAN#29]
I mnot able to understand where this problem in this line its showing error(d_loss_real = discriminator.train_on_batch(image_batch_hr, real_data_Y) but my images size(shape (96, 96, 3)), can you please where its problem

**Comment by sandhya9173** [comment]
![pic](https://user-images.githubusercontent.com/57871594/76930132-ce9a5900-690b-11ea-8816-50a65adf702a.jpg)
![pic2](https://user-images.githubusercontent.com/57871594/76930143-d528d080-690b-11ea-8641-e14855242dcd.jpg)

Both check please help in this error I mnot understanding

**Comment by deepak112** [comment]
You still facing this issue?

**Comment by sirius0503** [comment]
@deepak112 Hi Deepak, I am facing a similar issue could you please look at this thread here, I think it is a similar issue, except @sandhya9173 is trying to train the model, whereas I am trying to evaluate your pretrained model [issue](https://github.com/deepak112/Keras-SRGAN/issues/23#issuecomment-636659377)

**Comment by mustaeenqazi** [comment]
@deepak112   Hi Deepak iam facing the same issue while training, using the simplified code,  in Colab

**Comment by deepak112** [comment]
Hi, 
Can you please tell me shape of x_train_lr, x_train_hr, x_test_lr, x_test_hr in your code.

**Comment by mustaeenqazi** [comment]
thanks for prompt reply, here are the shapes:
x_train_lr = (500,) 
x_train_hr = (500,)
x_test_lr = (300,)
x_test_lr = (300,)

**Comment by deepak112** [comment]
Are all images are of same shape?

**Comment by mustaeenqazi** [comment]
![LOADING data and resizing](https://user-images.githubusercontent.com/66418760/83754967-232cb500-a66d-11ea-873e-90b5189dca21.png)

**Comment by mustaeenqazi** [comment]
shall i use the function  load_data_from_dirs_resize instead of load_data_from_dirs, to load the data?

**Comment by deepak112** [comment]
Ya images are not of same size. Either make one custom funtion to have same size images. And then save those images to some directory and then use  load_data_from_dirs.
