### ISSUE TITLE
Error while invoking test_lr_images

### ISSUE THREAD

**Issue by JordanMicahBennett** [deepak112/Keras-SRGAN#3]
After installing all requirements, trying to produce high res image fails, using command: 

python test.py --input_low_res="data_lr/" --output_dir="output/" --model_dir="model/gen_model3000.h5" --number_of_images=1 --test_type="test_lr_images"

Error reported:
![image](https://user-images.githubusercontent.com/3666405/56060164-9ec1f900-5d2b-11e9-8e14-2bf1cdb8da8a.png)

**Comment by deepak112** [comment]
Solved the issue.
