### ISSUE TITLE
Got error at the normalize part in simplified folder

### ISSUE THREAD

**Issue by niuyushuo** [deepak112/Keras-SRGAN#5]
Hi deepak112,

I follow the code in the simplified folder. Also i use the coco 2017 validation dataset as the training dataset, because the coco 2017 training dataset is too large. I just have an issue about running the noemalize part. After I load the dataset, when I run the normalize part, I will get the errors like:

ValueError                                Traceback (most recent call last)
<ipython-input-63-77f437a7a858> in <module>()
      3 print(type(x_train_hr))
      4 print(x_train_hr.shape)
----> 5 x_train_hr = normalize(x_train_hr)
      6 """
      7 x_train_lr = lr_images(train_dataset, 4)

<ipython-input-41-e6c65ae0b2d7> in normalize(input_data)
     37 
     38     #return (input_data.astype(np.float32) - 127.5)/127.5
---> 39     return (input_data.astype(np.float32))
     40 
     41 def denormalize(input_data):

ValueError: setting an array element with a sequence.

Could you help me to figure out this problem?  I really appreciate it.

**Comment by ajinkya933** [comment]
@niuyushuo  Did you solve this?

**Comment by deepak112** [comment]
How many images are you using for testing and try to check image properties and only use images with same properties.
Like you need to take images if same dimensions, check numbers of channels and also all images are not of RGB format.
Hope this helps.
