### ISSUE TITLE
Query regarding the generator loss returned

### ISSUE THREAD

**Issue by vibss2397** [deepak112/Keras-SRGAN#7]
So i implemented this srgan on a jupyter notebook and the losses that i am getting are something like :
discriminator_loss : 0.339855
gan_loss : [0.025425937, 0.023114227, 2.3117106]

can you tell what the third value in gan loss is, the first two i am assuming are content and adversarial loss

**Comment by deepak112** [comment]
Third one is combined loss. Like loss for complete network.
