### ISSUE TITLE
Number of image files are less then you specified

### ISSUE THREAD

**Issue by TrackLab** [deepak112/Keras-SRGAN#8]
I cropped the images all into 384x384.

Now I am getting the String 

> Number of image files are less then you specified
> Please reduce number of images to 486

I have 487 Pictures. When I delete one, it will tell me to reduce the Pictures to 485. It always goes back by one. Any Idea why? It is not giving any file/line error, it just gives back these 2 messages.

Or asking a bit differently: Where do I change the specified amount of Pictures? So I can use my smaller dataset. Or a bigger one, whatever I want. In what file/line do I change that?

**Comment by deepak112** [comment]
In your images there might be some png or grayscale image.
Actually I hardcoded code for particularly one type of images i.e jpeg in my case.

You can check Utils.py file. Line 92. That part of code is checking wether count of no of images given by you is equal to number of images in the folder satisfying condition of extension and of channels. From there I think u will get to know the flow. For your code you can remove that condition.

Thanks
