### ISSUE TITLE
Images are of not same shape 

### ISSUE THREAD

**Issue by sanahtech** [deepak112/Keras-SRGAN#9]
While training the model, I have used 595 image from COCO data-set. 
!python train.py --input_dir='./data/' --output_dir='./output/' --model_save_dir='./model/' --batch_size=64 --epochs=10 --number_of_images=595 --train_test_ratio=0.8
But getting the below error from Utils.py file  where len(test_array.shape) is 1 while it should be greater than 3.
**Images are of not same shape 
Please provide same shape images**

**Comment by deepak112** [comment]
Hi,
Yes images in COCO data-set are not of same shape, as well as some of them are gray scale. You need to resize images to same shape and you should also check for number of channels. Number of channels( len(test_array.shape) ) should always be 3.
